# Generated by Django 5.2.8 on 2025-11-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='current_balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__gte', 0)), name='customer_current_balance_gte_0'),
        ),
    ]
